---
- name: parser meta data
  parser_metadata:
    version: 1.0
    command: show interface
    network_os: ios

- name: match sections
  pattern_match:
    regex: "^(\\S+) is.*down,"
    match_all: yes
    match_greedy: yes
  register: section
  export: yes

- name: Build pattern group
  pattern_group:
    - name: match name
      pattern_match:
        regex: "^(\\S+)"
        content: "{{ item }}"
      register: name

    - name: match last input
      pattern_match:
        regex: "Last input\\s(\\S+),.*"
        content: "{{ item }}"
      register: last_input

    - name: match last output
      pattern_match:
        regex: "Last input.*, output\\s(\\S+),.*"
        content: "{{ item }}"
      register: last_output
  loop: "{{ section }}"
  register: interfaces
  export: yes

- name: generate JSON
  json_template:
    template:
      - key: "{{ item.name.matches.0 }}"
        object:
          - key: "name"
            value: "{{ item.name.matches.0 }}"
          - key: "input"
            value: "{{ item.last_input.matches.0 }}"
          - key: "output"
            value:  "{{ item.last_output.matches.0 }}"
  loop: "{{ interfaces }}"
  register: interface_facts
  export: yes
...
