---
- name: FIND FREE PORTS
  hosts: daves-switch
  gather_facts: no
  connection: network_cli

  roles:
    - ansible-network.network-engine

  tasks:
    - name: CAPTURE SHOW INTERFACE
      ios_command:
        commands:      
          - show interface
      register: output

    - name: PARSE OUTPUT
      command_parser:
        file: "parsers/show_int_parser.yml"
        content: "{{ output.stdout[0] }}"
    
    #- name: SHOW OUTPUT
    #  debug:
    #    var: interface_facts
    
    - name: GENERATE REPORT
      template:
        src: "templates/free_ports_template.j2"
        dest: "{{inventory_hostname}}_free_port.csv"