---
- name: FIND FREE PORTS
  hosts: sea
  gather_facts: no
  connection: network_cli

  roles:
    - ansible-network.network-engine

  tasks:
    - name: CAPTURE SHOW INTERFACE
      ios_command:
        commands:      
          - show interface
      register: output

    - name: PARSE OUTPUT
      command_parser:
        file: "parsers/show_int_parser.yml"
        content: "{{ output.stdout[0] }}"
    
    #- name: SHOW OUTPUT
    #  debug:
    #    var: interface_facts
    
    - name: GENERATE REPORTS
      template:
        src: "templates/free_ports_template.j2"
        dest: "reports/{{inventory_hostname}}_free_port.csv"
    
    - name: CONSOLIDATE FILES INTO ONE REPORT
      assemble:
        src: "reports/"
        dest: "reports/free_ports.csv"
      delegate_to: localhost
      run_once: yes

    - name: CLEAN UP FILES
      file:
        path: "reports/{{inventory_hostname}}_free_port.csv"
        state: absent
